# Generated by Django 5.2.5 on 2025-08-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_assessment_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
